spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stop-list
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 2358
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update
    open-in-view: false